spring:
  application:
    name: UniFest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      format_sql: true
      default_batch_fetch_size: 1000
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha
jwt:
  secret: ${JWT_SECRETKEY}
  access-token-expiration-minutes: 300000
  refresh-token-expiration-minutes: 10080
server:
  port: 8080


